# import = ["/home/daniel/.config/alacritty/themes/themes/kanagawa_wave.yaml"]
# save_to_clipboard = true
general.import = [
    # "~/.config/alacritty/themes/kanagawa_wave.toml"
    # "~/.config/alacritty/themes/one_dark.toml"
    "~/.config/alacritty/themes/kanagawa_contrast.toml"
    # "~/.config/alacritty/themes/modus_operandi.toml"
    # "~/.config/alacritty/themes/jellybeans.toml"
    # "~/.config/alacritty/themes/dayfox.toml"
]

[cursor.style]
blinking = "Off"
shape = "Beam"

[cursor.vi_mode_style]
blinking = "Off"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
# size = 12.5
size = 11.3
[font.normal]
family = "Hack Nerd Font"
# family = "Iosevka Nerd Font"
# family = "JetbrainsMono Nerd Font"
style = "Regular"




[font.offset]
x = 0
y = 1


[window]
opacity = 0.90

[window.padding]
x = 6
y = 4

[[keyboard.bindings]]
action = "ToggleViMode"
key = "q"
mode = "Vi"
