# import = ["/home/daniel/.config/alacritty/themes/themes/kanagawa_wave.yaml"]
# save_to_clipboard = true
general.import = [
    "~/.config/alacritty/themes/kanagawa_wave.toml"
    # "~/.config/alacritty/themes/kanagawa_neutral.toml"
    # "~/.config/alacritty/themes/jellybeans.toml"
    # "~/.config/alacritty/themes/dayfox.toml"
]

[cursor.style]
blinking = "Off"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.8

[font.normal]
family = "terminal-font"
style = "Regular"




[font.offset]
x = 0
y = 1


[window]
opacity = 0.90

[window.padding]
x = 6
y = 4

[[keyboard.bindings]]
action = "ToggleViMode"
key = "q"
mode = "Vi"
