# import = ["/home/daniel/.config/alacritty/themes/themes/kanagawa_wave.yaml"]
# save_to_clipboard = true
import = [
    # "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
    # "~/.config/alacritty/themes/themes/everforest_dark.toml"
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[cursor.style]
blinking = "On"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[font.offset]
x = 0
y = 1

[window]
opacity = 0.97

[window.padding]
x = 6
y = 6
