-- local keymap = vim.api.nvim_set_keymap
-- local opts = { noremap = true, silent = true }
-- local term_opts = { silent = true }
-- keymap("", "<Space>", "<Nop>", opts)
-- vim.g.mapleader = " "
-- vim.g.maplocalleader = " "
-- keymap("n", "<leader>ñ", ":lua new_md_file()<CR>", { noremap = true, silent = true })
-- keymap(
--   "n",
--   "<leader>nf",
--   ":Telescope find_files cwd=" .. "/home/daniel/Documentos/Dropbox/Notas" .. "<CR>",
--   { noremap = true, silent = true }
-- )
--
