#! /bin/sh

#Autostart
#nitrogen --restore &
xfce4-panel -d &
~/scripts/xmodmap.sh &
~/scripts/inicio.sh &
# ~/.screenlayout/compu-con-pantalla.sh &
xfce4-display.settings &
# nm-applet &
#xfdesktop -D &
sxhkd &

pgrep -x sxhkd >/dev/null || sxhkd &

# Más o menos funciona
# bspc monitor HDMI-0 -d 1 2 3 4 5
# bspc monitor eDP -d 6 7 8 9 0

monitor_externo=$(xrandr --query | grep 'HDMI-0 connected')
if [[ $monitor_externo = *connected* ]]; then
	xrandr --output HDMI-0 --auto --primary --right-of eDP
	# bspc wm -O eDP HDMI-0
	bspc monitor eDP -d - -
	bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
else
	xrandr --output eDP --auto --primary
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

# polybar -r &

bspc config border_width 3
bspc config window_gap 6
# bspc config top_padding 16
bspc config top_padding 20
bspc config single_monocle false
bspc config borderless_monocle true
bspc config click_to_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
#Kanagawa
bspc config normal_border_color "#2E3459"
bspc config active_border_color "#54546D"
bspc config focused_border_color "#5B65AB"
# bspc config focused_border_color "#7E9CD8"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"
#
# Gruvbox Material
# bspc config normal_border_color "#424a3e"
# bspc config active_border_color "#7c6f64"
# bspc config focused_border_color "#a89984"
# bspc config presel_feedback_color "#5e81ac"
# bspc config urgent_border_color "#dd2727"
#
# Graphite
# bspc config normal_border_color "##16161D"
# bspc config active_border_color "#323238"
# # bspc config focused_border_color "#ECE1C0"
# bspc config focused_border_color "#AFB8C6"
# bspc config presel_feedback_color "#5e81ac"
# bspc config urgent_border_color "#dd2727"

bspc rule --add Gpick state=floating
bspc rule -a Xfce4-panel state=floating border=off
bspc rule -a xfce4-popup-whiskermenu state=floating border=off
bspc rule -a Whisker\ Menu state=floating border=off
bspc rule -a Wrapper-2.0 state=floating border=off focus=on
bspc rule -a Zathura state=tiled
bspc rule -a Geary desktop=^9
bspc rule -a jetbrains-idea-ce desktop=^4
bspc rule -a gnome-calendar desktop=^7

sleep 5 && xprop -name "Whisker Menu"
picom --config ~/.config/picom/picom.conf &
~/.config/polybar/launch.sh &
