#! /bin/sh

~/scripts/inicio-bspwm.sh &
~/scripts/xpantallas-bspwm.sh &
# sleep 5 && xprop -name "Whisker Menu"

sleep 3; nm-applet &
sleep 1; pkill volumeicon &
sleep 1; pkill cbatticon &
$HOME/scripts/inicio.sh &
pkill copyq &

sleep 3; picom -b --config  $HOME/.config/picom/picom.conf
sleep 2; copyq &
sleep 3; volumeicon &
sleep 2; cbatticon &
# xfce4-display.settings &
sxhkd &
~/scripts/xmodmap.sh &
pgrep -x sxhkd >/dev/null || sxhkd &
pkill polybar &
~/.config/polybar/launch.sh &

# xfce4-panel -d &
feh --bg-fill /home/daniel/Imagenes/Fondos-de-pantalla/moon.jpg &

bspc config border_width 3
bspc config window_gap 5
bspc config bottom_padding 20
bspc config single_monocle false
bspc config borderless_monocle true
bspc config click_to_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####

#Kanagawa
bspc config normal_border_color "#2E3459"
bspc config active_border_color "#54546D"
bspc config focused_border_color "#5B65AB"
# bspc config focused_border_color "#7E9CD8"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

# Rules
bspc rule --add Gpick state=floating
bspc rule -a Xfce4-panel state=floating border=off
bspc rule -a xfce4-popup-whiskermenu state=floating border=off
bspc rule -a Whisker\ Menu state=floating border=off
bspc rule -a Wrapper-2.0 state=floating border=off focus=on
bspc rule -a Zathura state=tiled

# if [[ $monitor_externo = *connected* ]]; then
# 	bspc rule -a jetbrains-idea-ce desktop=^4
# 	bspc rule -a jetbrains-idea desktop=^4
# 	bspc rule -a Geary desktop=^9
# 	bspc rule -a gnome-calendar desktop=^7
# else
# 	bspc rule -a jetbrains-idea-ce desktop=^2
# 	bspc rule -a jetbrains-idea desktop=^2
# 	bspc rule -a Geary desktop=^7
# 	bspc rule -a gnome-calendar desktop=^5
# fi
