#! /bin/sh

~/.config/bspwm/autostart.sh &

bspc config border_width 3
bspc config window_gap 3
# bspc config bottom_padding 14
bspc config single_monocle false
bspc config borderless_monocle true
bspc config click_to_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####

#Desert
bspc config normal_border_color "#1E1E1E"
bspc config active_border_color "#3F3F3F"
bspc config focused_border_color "#7e9CD8"
# bspc config focused_border_color "#7E9CD8"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

# Rules
bspc rule -a Gpick state=floating
bspc rule -a copyq state=floating
bspc rule -a Xfce4-panel state=floating border=off
bspc rule -a xfce4-popup-whiskermenu state=floating border=off
bspc rule -a Whisker\ Menu state=floating border=off
bspc rule -a Wrapper-2.0 state=floating border=off focus=on
bspc rule -a Zathura state=tiled
