--dark
vim.cmd.colorscheme 'kanagawa-wave'
-- vim.cmd.colorscheme 'melange'
-- vim.cmd.colorscheme 'vague'
-- vim.cmd.colorscheme 'mellifluous'
-- vim.cmd.colorscheme 'gruvbox-material'
-- vim.cmd.colorscheme 'monet'
-- vim.cmd.colorscheme 'rose-pine-main'
-- light
-- vim.cmd.colorscheme 'kanagawa-lotus'
-- vim.cmd.colorscheme 'monokai-nightasty'
-- vim.cmd.colorscheme 'maron'
-- vim.cmd.colorscheme 'rasmus'
