return {
  "Eutrius/Otree.nvim",
  lazy = false,
  vscode = false,
  dependencies = {
    "stevearc/oil.nvim",
  },
  opts = {
    win_size = 40,
    open_on_left = true,

    show_hidden = true,
    show_ignore = true,
    git_signs = true,
    use_default_keymaps = false,
    lsp_signs = true,
    oil = "",
    keymaps = { -- See |Otree-keybindings|
      ["<CR>"] = "actions.select",
      ["l"] = "actions.select",
      ["h"] = "actions.close_dir",
      ["q"] = "actions.close_win",
      ["<C-h>"] = "actions.goto_parent",
      ["<C-l>"] = "actions.goto_dir",
      ["<M-h>"] = "actions.goto_home_dir",
      ["cd"] = "actions.change_home_dir",
      ["L"] = "actions.open_dirs",
      ["H"] = "actions.close_dirs",
      ["o"] = "actions.oil_dir",
      ["O"] = "actions.oil_into_dir",
      ["<C-t>"] = "actions.open_tab",
      ["<C-v>"] = "actions.open_vsplit",
      ["<C-s>"] = "actions.open_split",
      ["."] = "actions.toggle_hidden",
      ["i"] = "actions.toggle_ignore",
      ["r"] = "actions.refresh",
      ["f"] = "actions.focus_file",
      ["?"] = "actions.open_help",
    },
  },
  keys = {
    -- { "<leader>e", "<CMD>Otree<CR>", desc = "Explorer" },
  },
}
